# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18 # Use a compatible Node.js version

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    - name: Upload artifact for Pages
      uses: actions/upload-pages-artifact@v3
      with:
         path: ./ 

    # Step 4: Build the project (compile TypeScript)
    - name: Build Project
      run: |
        npx tsc

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
